Repository ManageIQ/manageiq-appliance_console, pull requests merged in 2018-05, with the labels that each got.

#38 Always configure database.yml and encryption key
  bin/appliance_console
  lib/manageiq/appliance_console/database_replication_standby.rb
  lib/manageiq/appliance_console/internal_database_configuration.rb
  spec/database_replication_standby_spec.rb
Labels: blocker, bug

#39 Fix the ensure_key_configured helper method
  bin/appliance_console
Labels: blocker, bug

#41 Add .ruby-version to .gitignore
  .gitignore
Labels: developer

#34 Validate the encryption key when configuring the database
  lib/manageiq/appliance_console/database_configuration.rb
  spec/database_configuration_spec.rb
Labels: bug

#42 Refactors dbrestore action into a class
  bin/appliance_console
  lib/manageiq-appliance_console.rb
  lib/manageiq/appliance_console/database_admin.rb
  lib/manageiq/appliance_console/i18n.rb
  spec/database_admin_spec.rb
  spec/prompts_spec.rb
  spec/support/ui.rb
Labels: enhancement, refactoring

#43 Bump to ruby 2.4.4 for great justice
  .travis.yml
Labels: test

#45 Add dbdump action
  bin/appliance_console
  lib/manageiq/appliance_console/database_admin.rb
  locales/appliance/en.yml
  spec/database_admin_spec.rb
Labels: enhancement
