Repository ManageIQ/manageiq-appliance_console, pull requests merged in 2019-03, with the labels that each got.

#83 Handle existing certs and support retun of cert generation
  lib/manageiq/appliance_console/certificate.rb
  spec/certificate_authority_spec.rb
  spec/certificate_spec.rb
Labels: bug

#82 Update repmgrd service name for postgres 10
  lib/manageiq/appliance_console/database_replication.rb
  lib/manageiq/appliance_console/database_replication_standby.rb
  lib/manageiq/appliance_console/internal_database_configuration.rb
  spec/database_replication_spec.rb
Labels: enhancement

#84 Fix permissions on PG user home directory after disk mount
  lib/manageiq/appliance_console/internal_database_configuration.rb
  manageiq-appliance_console.gemspec
  spec/internal_database_configuration_spec.rb
Labels: bug

#85 Add Ruby 2.5 support
  .travis.yml
Labels: dependencies

#86 Remove references to MiqPassword
  bin/appliance_console
  lib/manageiq/appliance_console/database_configuration.rb
  lib/manageiq/appliance_console/key_configuration.rb
  manageiq-appliance_console.gemspec
  spec/database_configuration_spec.rb
  spec/internal_database_configuration_spec.rb
  spec/key_configuration_spec.rb
  spec/spec_helper.rb
  spec/support/v2_key
Labels: technical debt
