Repository ManageIQ/manageiq-appliance_console, pull requests merged in 2019-12, with the labels that each got.

#105 Fix SCAP remediation
  lib/manageiq/appliance_console/scap.rb
  manageiq-appliance_console.gemspec
Labels: blocker, bug

#98 [RFE] Add openscap functionality to appliance_console_cli
  lib/manageiq/appliance_console/cli.rb
Labels: enhancement, unmergeable

#106 update hostname regex to allow starting with digit
  lib/manageiq/appliance_console/prompts.rb
  spec/prompts_spec.rb
Labels: bug
