Repository ManageIQ/manageiq-appliance_console, pull requests merged in 2019-05, with the labels that each got.

#89 Bump master travis.yml to ruby 2.4.6
  .travis.yml
Labels: changelog/no, test

#90 Pull in version 1.2.3 of linux admin for nvme device fix
  manageiq-appliance_console.gemspec
Labels: bug

#88 Remove pg cert handling
  bin/appliance_console
  lib/manageiq/appliance_console/certificate_authority.rb
  lib/manageiq/appliance_console/cli.rb
  spec/certificate_authority_spec.rb
  spec/cli_spec.rb
  spec/support/trollop.rb
Labels: bug, changelog/yes

#91 Do not attempt to restore db if evmserverd is running
  lib/manageiq/appliance_console/database_admin.rb
  spec/database_admin_spec.rb
Labels: changelog/yes, enhancement
