Repository ManageIQ/manageiq-appliance_console, pull requests merged in 2020-10, with the labels that each got.

#126 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: dependencies

#131 correct gem name in comment
  Gemfile
Labels: bug, developer, documentation

#127 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-appliance_console.gemspec
Labels: developer, enhancement

#132 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer
