Repository ManageIQ/manageiq-appliance_console, pull requests merged in 2020-05, with the labels that each got.

#117 Add support for the oidc introspection endpoint
  lib/manageiq/appliance_console/cli.rb
  lib/manageiq/appliance_console/oidc_authentication.rb
  spec/oidc_authentication_spec.rb
Labels: enhancement

#120 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer, documentation

#122 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#121 Try to fetch introspect endpoint from the provider metadata
  lib/manageiq/appliance_console/cli.rb
  lib/manageiq/appliance_console/oidc_authentication.rb
  spec/oidc_authentication_spec.rb
Labels: enhancement
