Repository ManageIQ/manageiq-appliance_console, pull requests merged in 2020-04, with the labels that each got.

#113 Add net-ssh gems needed to support ed25519 cipher
  manageiq-appliance_console.gemspec
Labels: bug

#115 Top level constant warnings in specs
  spec/database_replication_primary_spec.rb
  spec/database_replication_spec.rb
  spec/database_replication_standby_spec.rb
Labels: cleanup, test

#114 Messaging configuration
  bin/appliance_console
  lib/manageiq-appliance_console.rb
  lib/manageiq/appliance_console/cli.rb
  lib/manageiq/appliance_console/messaging_configuration.rb
  locales/appliance/en.yml
  locales/container/en.yml
  spec/cli_spec.rb
  spec/messaging_configuration_spec.rb
Labels: enhancement

#116 rename Configure Application Database Failover Monitor
  locales/appliance/en.yml
  locales/container/en.yml
Labels: bug
