Repository ManageIQ/manageiq-appliance_console, pull requests merged in 2023-05, with the labels that each got.

#211 Double escape @ in realm to avoid shell interpretation
  lib/manageiq/appliance_console/principal.rb
  spec/certificate_spec.rb
  spec/principal_spec.rb
Labels: bug

#208 Move gem name loader to proper namespaced location.
  bin/appliance_console
  bin/appliance_console_cli
  lib/manageiq/appliance_console.rb
  spec/spec_helper.rb
  spec/support/ui.rb
Labels: enhancement

#210 Clean up test output (highline and stdout messages)
  spec/certificate_authority_spec.rb
  spec/cli_spec.rb
  spec/database_admin_spec.rb
  spec/database_configuration_spec.rb
  spec/internal_database_configuration_spec.rb
  spec/message_configuration_server_spec.rb
  spec/prompts_spec.rb
  spec/support/ui.rb
Labels: test

#213 Add historical entries to the CHANGELOG
  CHANGELOG.md
Labels: documentation
