Repository ManageIQ/manageiq-appliance_console, pull requests merged in 2024-01, with the labels that each got.

#226 Allow rails 7 gems in gemspec
  .github/workflows/ci.yaml
  Gemfile
  manageiq-appliance_console.gemspec
  spec/spec_helper.rb
Labels: dependencies, rails7

#227 Add ruby 3.1 to the test matrix
  .github/workflows/ci.yaml
  lib/manageiq/appliance_console/message_configuration.rb
Labels: dependencies, test

#228 Change the Name of the CA from something to ApplianceCA
  lib/manageiq/appliance_console/message_configuration_server.rb
Labels: enhancement
